services:
  face-detection-2:
    image: ghcr.io/cdegrel/face-detection-2:latest
    ports:
      - "5005:5005"
    volumes:
      - ./db.json:/app/db.json
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
